# Generated by Django 4.0.3 on 2022-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_blogs_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
