# Generated by Django 4.0.3 on 2022-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_plots_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='picture',
            field=models.ImageField(upload_to='agentimages'),
        ),
    ]
