# Generated by Django 4.0.3 on 2022-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_agents_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='picture',
            field=models.ImageField(upload_to='agentImages'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='picture',
            field=models.ImageField(upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='picture',
            field=models.ImageField(upload_to='clientImages'),
        ),
        migrations.AlterField(
            model_name='plots',
            name='picture',
            field=models.ImageField(upload_to='plotImages'),
        ),
    ]
